language: objective-c
cache: cocoapods

before_install:
  - sudo easy_install cpp-coveralls
  - sudo gem install cocoapods
  - brew update
  - brew upgrade xctool

script:
  - make coverage

after_success:
  - make send-to-coveralls
